### ISSUE TITLE
Is there the camera extrinsics provided?

### ISSUE THREAD

**Issue by dyfcalid** [once-3dlanes/once_3dlanes_benchmark#1]
Wonderful work. I found that in the ONCE-3DLanes dataset only the intrinsics data of the camera are provided, and in the original ONCE dataset annotation I only found the extrinsics data from camera to lidar, but there is no transformation matrix from the camera coordinate system to the vehicle coordinate system. 
So is it possible to get the extrinsics of the camera, or in another way the height and pitch angle of the camera, so that we can the transform the images from front view to the bird eye's view?

**Comment by once-3dlanes** [comment]
thanks for the questions

Unfortunately, ONCE dataset does not release such extrinsics as well as height and pitch angle of the data.
In our 3D lane annotation method, the camera extrinsics are also not needed.
So we are sorry to say the extrinsics are unavailable at present

**Comment by dyfcalid** [comment]
Thank you.
Btw, I'm very interested in your work and would like to ask when you can release your "SALAD" model and the pretrained checkpoint. Do you have the plan for it?
Looking forward to your reply.

**Comment by nick112358** [comment]
We are currently working on 2D lane detection method based on SALAD. In the coming future, 2D lane detection based work will be released, and we will open source it as well as the checkpoint into this repository.

**Comment by rocinant** [comment]
The dataset itself is great, but it is a pity that extrinsics along with 3d lane coordinators are not provided. Because in auto industry, people really do not care about coordinators in camera coordinator system but coordinators in BEV or vehicle system are used for down-stream work such as plan and control. There is actually a huge gap between coordinators in camera coordinator system to vehicle, because image to camera system is actually just with an intrinsics which is normally fixed and easy to learn but image to real BEV where you get extrinsics involved is where things get tricky and tons of studies struggled with but this dataset and paper failed to solve.
